apiVersion: apps/v1
kind: Deployment
metadata:
  name: tamy-app
  labels:
    app: tamy-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tamy-app
  template:
    metadata:
      labels:
        app: tamy-app
    spec:
      containers:
        - name: tamy-app
          image: image: quay.io/podman/stable:latest
          ports:
            - containerPort: 8080
